### ISSUE TITLE
sponsors: summary page

### ISSUE THREAD

**Issue by louking** [louking/contracts#197]
@hhlanglois please advise as to content

**Comment by louking** [comment]
* sticky filter by race
* summary table by level
* yearly table (last 5 years)
  * columns by year (current first)
  * total $
  * avr $
  * n (number of 
* weekly table
  * columns by year (current first)
  * weeks starting Jan 1 of year
  * weeks ending week of race
  * total sponsor $ accumulated by week

* charts
  * sponsorship $ trends by year (same # years as yearly table)
  * stacked $ bar by trend (new, same, up, down) [by year?]

**Comment by hhlanglois** [comment]
I'm more interested in numbers for comparing previous to current year (up, down, same, etc) rather than a chart. N and total $ for new, up, down, same.  It's more difficult to add N and total $ for sponsorships lost from previous year. I've got a separate table for that now that I update manually. The sum of all these shows the net $$ for the year (so far). 

I haven't really gotten going on this yet for 2019, but I also do expo management from my sponsor sheet with summary that gives me totals for Yes, No, N/A and unknown.  I don't think I've given you any requirements for that, so I'm OK to do it manually, at least for this year.

**Comment by louking** [comment]
I've updated the issue comment - is this about right now?
