### ISSUE TITLE
On race day, race registrations doesn't update to include new registrations for Rick's Run

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#428]
273 in the early morning. RSU says 277 later in the afternoon, but the race registration plot in contractility still shows 273.

**Comment by louking** [comment]
Late race day, @hhlanglois noticed RSU showed 277, but the race summary view showed 273. As mentioned, for some reason when we ask RSU for registrations modified since the last cache time, they leave out new registrations, so this is a bug and now the new software also asks for registrations added since the last cache time, combining the two lists.

But I also mentioned that the charts stop tracking at the end of the last event.

There were two additional entries added after the end of the last event

1. an "unknown participant" as a nonbinary runner of the 8 hour challenge
2. someone who was apparently transferred from the 8 hour challenge to the virtual version

Because the transfer occurred after the event completed, but the previous registration was before the event completed, this registration won't show up in the chart. Therefore the chart will show 276 even tho there were actually 277 on race day.

I am not planning on doing anything about this.
